### ISSUE TITLE
Amp Stack: two parameters are not restored when loading a preset

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix.vst#3] opened 2023-01-23 21:10 UTC
Two parameters in the Amp Stack are not restored correctly when loading a preset, but rather seem to be restored to their default value:
- Pre gain
- Drive

**Comment by brummer10** [comment] 2023-01-25 11:06
Hi
Thanks for reporting the issue. I checked it and could reproduce it. I know as well what the issue is. Unfortunately I'm in the middle of restructuring the source code to fit better the needs of running guitarix as plugin. In the current fashion I can't push anything to guitarix without the risk of break the stand alone code. It would take several weeks before I reach a committable state again.

If you would make your hands dirty you could fix it for yourself, open 
 guitarix.vst/guitarix/trunk/src/gx_head/engine/gx_preset.cpp go to line 463 and replace:

```
        if (p->id() == "amp2.stage1.Pregain" || p->id() == "gxdistortion.drive") {
            gx_engine::FloatParameter& pf = p->getFloat();
            pf.rampJSON_value(jp);
        } else {
            p->readJSON_value(jp);
        }
```
with just
`      p->readJSON_value(jp);`

**Comment by Gimmeapill** [comment] 2023-01-25 21:43
Thanks Hermann!
There's no hurry at all, it's already super great that you got it working ;-)

**Comment by brummer10** [comment] 2023-01-26 07:22
If you found more bugs, please report them here so I could fix them in the code rework run.

**Comment by Gimmeapill** [comment] 2023-01-29 11:02
Confirmed: with the patch pre-gain and drive are now restored properly. I'll test further and report any oddity.

**Comment by brummer10** [comment] 2023-02-02 04:29
I've pushed the fix now to the repositories. Including a additional fix for bank/preset loading.
Still, guitarix.vst wouldn't work on ardour official builds because of library mismatches. 
It works on distribution versions of ardour, true.

**Closed** 2023-02-02 11:22 UTC
